services:
  app:
    container_name: flask_01
    build: .
    image: flask_app
    ports:
      - "5050:5000"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:5000/"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
